In [1]:
#Importing Libraries
import warnings
import numpy as np
import pandas as pd
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.feature_selection import RFE
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
warnings.filterwarnings("ignore")

In [3]:
#Loading the Dataset
dataset = pd.read_csv("Preprocessed_Dataset_Numerical.csv")

In [4]:
dataset

,Age,Income,LoanAmount,CreditScore,InterestRate,LoanTerm,Education_High School,Education_Master's,Education_PhD,EmploymentType_Part-time,EmploymentType_Self-employed,EmploymentType_Unemployed,MaritalStatus_Married,MaritalStatus_Single,LoanPurpose_Business,LoanPurpose_Education,LoanPurpose_Home,LoanPurpose_Other,Default
0,57.0,109874.0,30973.0,567.0,13.95,60.0,0,0,0,1,0,0,0,0,0,0,0,0,0
1,69.0,34006.0,112148.0,597.0,10.60,24.0,0,0,0,1,0,0,1,0,0,0,0,0,1
2,20.0,36779.0,135741.0,352.0,23.82,36.0,0,0,0,0,0,0,0,0,0,0,0,0,1
3,41.0,50628.0,82083.0,828.0,11.32,48.0,1,0,0,0,0,0,0,0,0,0,0,0,1
4,28.0,114840.0,246968.0,415.0,22.65,24.0,1,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,20.0,143934.0,105532.0,521.0,14.66,24.0,0,0,0,0,0,0,1,0,0,0,0,0,1
49996,47.0,139079.0,102610.0,669.0,17.28,24.0,0,0,0,0,0,1,0,0,0,0,0,0,0
49997,32.0,106367.0,85207.0,466.0,2.44,36.0,0,0,0,0,0,0,0,0,0,0,0,0,0
49998,29.0,94936.0,45806.0,313.0,24.81,48.0,0,0,0,0,0,0,0,1,0,0,0,0,1
49999,28.0,115166.0,211439.0,461.0,24.79,60.0,0,0,0,0,0,0,0,0,0,0,0,0,1

In [5]:
dataset = pd.get_dummies(dataset, dtype = int, drop_first = True)

In [6]:
dataset

,Age,Income,LoanAmount,CreditScore,InterestRate,LoanTerm,Education_High School,Education_Master's,Education_PhD,EmploymentType_Part-time,EmploymentType_Self-employed,EmploymentType_Unemployed,MaritalStatus_Married,MaritalStatus_Single,LoanPurpose_Business,LoanPurpose_Education,LoanPurpose_Home,LoanPurpose_Other,Default
0,57.0,109874.0,30973.0,567.0,13.95,60.0,0,0,0,1,0,0,0,0,0,0,0,0,0
1,69.0,34006.0,112148.0,597.0,10.60,24.0,0,0,0,1,0,0,1,0,0,0,0,0,1
2,20.0,36779.0,135741.0,352.0,23.82,36.0,0,0,0,0,0,0,0,0,0,0,0,0,1
3,41.0,50628.0,82083.0,828.0,11.32,48.0,1,0,0,0,0,0,0,0,0,0,0,0,1
4,28.0,114840.0,246968.0,415.0,22.65,24.0,1,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,20.0,143934.0,105532.0,521.0,14.66,24.0,0,0,0,0,0,0,1,0,0,0,0,0,1
49996,47.0,139079.0,102610.0,669.0,17.28,24.0,0,0,0,0,0,1,0,0,0,0,0,0,0
49997,32.0,106367.0,85207.0,466.0,2.44,36.0,0,0,0,0,0,0,0,0,0,0,0,0,0
49998,29.0,94936.0,45806.0,313.0,24.81,48.0,0,0,0,0,0,0,0,1,0,0,0,0,1
49999,28.0,115166.0,211439.0,461.0,24.79,60.0,0,0,0,0,0,0,0,0,0,0,0,0,1

In [7]:
independent = dataset.drop("Default",axis = 1)
dependent = dataset["Default"]

In [8]:
independent

,Age,Income,LoanAmount,CreditScore,InterestRate,LoanTerm,Education_High School,Education_Master's,Education_PhD,EmploymentType_Part-time,EmploymentType_Self-employed,EmploymentType_Unemployed,MaritalStatus_Married,MaritalStatus_Single,LoanPurpose_Business,LoanPurpose_Education,LoanPurpose_Home,LoanPurpose_Other
0,57.0,109874.0,30973.0,567.0,13.95,60.0,0,0,0,1,0,0,0,0,0,0,0,0
1,69.0,34006.0,112148.0,597.0,10.60,24.0,0,0,0,1,0,0,1,0,0,0,0,0
2,20.0,36779.0,135741.0,352.0,23.82,36.0,0,0,0,0,0,0,0,0,0,0,0,0
3,41.0,50628.0,82083.0,828.0,11.32,48.0,1,0,0,0,0,0,0,0,0,0,0,0
4,28.0,114840.0,246968.0,415.0,22.65,24.0,1,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,20.0,143934.0,105532.0,521.0,14.66,24.0,0,0,0,0,0,0,1,0,0,0,0,0
49996,47.0,139079.0,102610.0,669.0,17.28,24.0,0,0,0,0,0,1,0,0,0,0,0,0
49997,32.0,106367.0,85207.0,466.0,2.44,36.0,0,0,0,0,0,0,0,0,0,0,0,0
49998,29.0,94936.0,45806.0,313.0,24.81,48.0,0,0,0,0,0,0,0,1,0,0,0,0
49999,28.0,115166.0,211439.0,461.0,24.79,60.0,0,0,0,0,0,0,0,0,0,0,0,0

In [9]:
dependent

0        0
1        1
2        1
3        1
4        0
        ..
49995    1
49996    0
49997    0
49998    1
49999    1
Name: Default, Length: 50000, dtype: int64

In [ ]:
#Finding best Features Using RFE
n = 7
rfe_list = []
lr = LogisticRegression(solver = 'lbfgs')
rf = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0) 
dt = DecisionTreeClassifier(criterion = 'gini', max_features = 'sqrt', random_state = 0) 
svc = SVC(kernel = 'linear', random_state = 0)
classification_models = [lr, rf, dt, svc,]  
for model in classification_models:
    rfe_obj = RFE(model,n_features_to_select = n)
    rfe_model = rfe_obj.fit(independent,dependent)
    rfe_feature = rfe_model.transform(independent)
    rfe_list.append(rfe_feature)

rfe_list

In [ ]:
lg_accuracy = []
rf_accuracy = []
dt_accuracy = []
knn_accuracy = []
nb_accuracy = []
svc_linear_accuracy = []
svc_non_linear_accuracy = []

In [ ]:
for i in rfe_list:
    x_train, x_test, y_train, y_test = train_test_split(i,dependent,test_size = 0.20, random_state = 0)

    #Logistic Regresssion
    lr_classifier = LogisticRegression(random_state = 0)
    lr_classifier.fit(x_train, y_train)
    y_pred = lr_classifier.predict(x_test) 
    lg_cm = confusion_matrix(y_test, y_pred) 
    lg_acc=accuracy_score(y_test, y_pred )
    lg_report=classification_report(y_test, y_pred) 
    lg_accuracy.append(lg_acc)
    print(lg_acc)

    #SVM Linear
    svc_classifier =  SVC(kernel = 'linear', random_state = 0)
    svc_classifier.fit(x_train, y_train)
    y_pred = svc_classifier.predict(x_test) 
    svc_cm = confusion_matrix(y_test, y_pred) 
    svc_accuracy=accuracy_score(y_test, y_pred )
    svc_report=classification_report(y_test, y_pred) 
    svc_linear_accuracy.append(svc_accuracy)    
    print(svc_accuracy)

    #SVM Non Linear
    svc_n_classifier =  SVC(kernel = 'rbf', random_state = 0)
    svc_n_classifier.fit(x_train, y_train)
    y_pred = svc_n_classifier.predict(x_test) 
    svc_n_cm = confusion_matrix(y_test, y_pred) 
    svc_n_accuracy=accuracy_score(y_test, y_pred )
    svc_n_report=classification_report(y_test, y_pred) 
    svc_non_linear_accuracy.append(svc_n_accuracy)  
    print(svc_n_accuracy)
    
    #Random Forest
    rf_classifier =  RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
    rf_classifier.fit(x_train, y_train)
    y_pred = rf_classifier.predict(x_test) 
    rf_cm = confusion_matrix(y_test, y_pred) 
    rf_acc=accuracy_score(y_test, y_pred )
    rf_report=classification_report(y_test, y_pred) 
    rf_accuracy.append(rf_acc)  
    print(rf_acc)

    #Decistion Tree
    dt_classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
    dt_classifier.fit(x_train, y_train)
    y_pred = dt_classifier.predict(x_test) 
    cm = confusion_matrix(y_test, y_pred) 
    dt_acc=accuracy_score(y_test, y_pred )
    dt_report=classification_report(y_test, y_pred) 
    dt_accuracy.append(dt_acc)  
    print(dt_acc)
  
    #KNN
    knn_classifier =  KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
    knn_classifier.fit(x_train, y_train)
    y_pred = knn_classifier.predict(x_test) 
    knn_cm = confusion_matrix(y_test, y_pred) 
    knn_acc=accuracy_score(y_test, y_pred )
    knn_report=classification_report(y_test, y_pred) 
    knn_accuracy.append(knn_acc)  
    print(knn_accuracy)

    #Naive Baye's
    nb_classifier = GaussianNB()
    nb_classifier.fit(x_train, y_train)
    y_pred = nb_classifier.predict(x_test) 
    nb_cm = confusion_matrix(y_test, y_pred) 
    nb_accy=accuracy_score(y_test, y_pred )
    nb_report=classification_report(y_test, y_pred) 
    nb_accuracy.append(nb_accy)  
    print(nb_accy)

In [ ]:
rfe_data = pd.DataFrame(index = ["Logistic","SVC","Random","DecisitionTree"],columns = ["Logistic","SVM_Linear","SVM_Non_Linear",
                                                                                              "KNN","Navie","Decision","Random"])

In [ ]:
rfe_data

In [ ]:
for index,col in enumerate(rfe_data.index):        
    rfe_data["Logistic"][col]        = lg_accuracy[0]
    rfe_data["SVM_Linear"][col]      = svc_linear_accuracy[0]
    rfe_data["SVM_Non_Linear"][col]  = svc_non_linear_accuracy[0]
    rfe_data["KNN"][col]             = knn_accuracy[0]
    rfe_data["Navie"][col]           = nb_accuracy[0]
    rfe_data["Decision"][col]        = dt_accuracy[0]
    rfe_data["Random"][col]          = rf_accuracy[0]

In [ ]:
#k = 5
rfe_data

In [ ]:
#k = 12
rfe_data

In [ ]:
#k = 15
rfe_data