In [1]:
#Loading Libraries
import pandas as pd
import pickle
import warnings
import numpy as np
from sklearn.svm import SVC
from sklearn.impute import SimpleImputer
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import ComplementNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import CategoricalNB 
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
warnings.filterwarnings("ignore")

In [3]:
#Loading Dataset
dataset = pd.read_csv("Preprocessed_Dataset_Numerical.csv")
dataset

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education_High School,...,MaritalStatus_Married,MaritalStatus_Single,HasMortgage_Yes,HasDependents_Yes,LoanPurpose_Business,LoanPurpose_Education,LoanPurpose_Home,LoanPurpose_Other,HasCoSigner_Yes,Default
0,48.0,90754.0,5902.0,462.0,91.0,2.0,10.46,60.0,0.80,0,...,1,0,0,0,0,0,0,0,1,0
1,24.0,59193.0,90049.0,309.0,73.0,1.0,20.85,36.0,0.88,1,...,0,1,1,0,0,0,0,0,1,0
2,55.0,77343.0,204141.0,423.0,19.0,2.0,17.66,48.0,0.49,0,...,0,0,1,0,0,0,0,0,1,0
3,18.0,25087.0,15645.0,474.0,23.0,4.0,20.95,48.0,0.58,0,...,0,0,0,0,0,0,0,0,1,0
4,31.0,33215.0,235022.0,771.0,67.0,3.0,10.53,36.0,0.90,0,...,0,1,1,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,59.0,127901.0,46482.0,424.0,44.0,4.0,15.27,60.0,0.58,0,...,0,0,0,1,0,0,0,0,0,1
996,54.0,139677.0,138362.0,780.0,27.0,3.0,11.82,24.0,0.49,0,...,0,1,1,0,0,0,0,0,0,1
997,42.0,53038.0,62256.0,763.0,116.0,3.0,2.55,36.0,0.54,0,...,0,0,1,0,0,0,0,0,1,0
998,43.0,137420.0,116698.0,424.0,21.0,4.0,9.43,36.0,0.85,0,...,0,0,0,0,0,0,0,0,0,1
999,48.0,33362.0,205046.0,750.0,2.0,2.0,4.37,60.0,0.37,1,...,1,0,0,0,0,0,0,0,1,1

In [4]:
dataset.columns

Index(['Age', 'Income', 'LoanAmount', 'CreditScore', 'MonthsEmployed',
       'NumCreditLines', 'InterestRate', 'LoanTerm', 'DTIRatio',
       'Education_High School', 'Education_Master's', 'Education_PhD',
       'EmploymentType_Part-time', 'EmploymentType_Self-employed',
       'EmploymentType_Unemployed', 'MaritalStatus_Married',
       'MaritalStatus_Single', 'HasMortgage_Yes', 'HasDependents_Yes',
       'LoanPurpose_Business', 'LoanPurpose_Education', 'LoanPurpose_Home',
       'LoanPurpose_Other', 'HasCoSigner_Yes', 'Default'],
      dtype='object')

In [5]:
independent = dataset.drop(["Default"],axis = 1)
dependent = dataset[["Default"]]

In [6]:
independent.head()

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education_High School,...,EmploymentType_Unemployed,MaritalStatus_Married,MaritalStatus_Single,HasMortgage_Yes,HasDependents_Yes,LoanPurpose_Business,LoanPurpose_Education,LoanPurpose_Home,LoanPurpose_Other,HasCoSigner_Yes
0,48.0,90754.0,5902.0,462.0,91.0,2.0,10.46,60.0,0.80,0,...,0,1,0,0,0,0,0,0,0,1
1,24.0,59193.0,90049.0,309.0,73.0,1.0,20.85,36.0,0.88,1,...,0,0,1,1,0,0,0,0,0,1
2,55.0,77343.0,204141.0,423.0,19.0,2.0,17.66,48.0,0.49,0,...,0,0,0,1,0,0,0,0,0,1
3,18.0,25087.0,15645.0,474.0,23.0,4.0,20.95,48.0,0.58,0,...,0,0,0,0,0,0,0,0,0,1
4,31.0,33215.0,235022.0,771.0,67.0,3.0,10.53,36.0,0.90,0,...,0,0,1,1,0,0,0,0,0,0

In [7]:
dependent.head()

   Default
0        0
1        0
2        0
3        0
4        1

In [8]:
independent.isnull().sum()

Age                             0
Income                          0
LoanAmount                      0
CreditScore                     0
MonthsEmployed                  0
NumCreditLines                  0
InterestRate                    0
LoanTerm                        0
DTIRatio                        0
Education_High School           0
Education_Master's              0
Education_PhD                   0
EmploymentType_Part-time        0
EmploymentType_Self-employed    0
EmploymentType_Unemployed       0
MaritalStatus_Married           0
MaritalStatus_Single            0
HasMortgage_Yes                 0
HasDependents_Yes               0
LoanPurpose_Business            0
LoanPurpose_Education           0
LoanPurpose_Home                0
LoanPurpose_Other               0
HasCoSigner_Yes                 0
dtype: int64

In [9]:
x_train,x_test,y_train,y_test = train_test_split(independent,dependent, test_size = 0.2,random_state = 42)

In [10]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
x_train

array([[ 0.32735045, -1.24352985,  0.29935727, ...,  0.        ,
         0.        , -1.02275892],
       [-1.44388446,  0.28046633, -1.54867062, ...,  0.        ,
         0.        , -1.02275892],
       [ 1.37697114,  0.712488  , -1.78336971, ...,  0.        ,
         0.        ,  0.97774752],
       ...,
       [ 0.65535692, -0.4881137 , -1.24952676, ...,  0.        ,
         0.        , -1.02275892],
       [-0.72227024, -0.14055193, -1.72831292, ...,  0.        ,
         0.        , -1.02275892],
       [-0.45986507, -1.21501647,  0.80903704, ...,  0.        ,
         0.        ,  0.97774752]])

 SVM Model

In [11]:
svc_params = {   
   "kernel" : ["rbf","sigmoid","linear"],   
   "C"      : [100,150],     
   "gamma"   : ["scale", "auto"]
}
svc_classifier = GridSearchCV(SVC(),svc_params, refit = True)  
svc_classifier.fit(x_train,y_train) 
print(svc_classifier.best_params_)

{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}

In [12]:
# svc_classifier = SVC()
# svc_classifier.fit(x_train,y_train)

In [13]:
#Predicting
y_svc_pred = svc_classifier.predict(x_test)

#finding Confustion Matrix
svc_confusion_mtx = confusion_matrix(y_test,y_svc_pred)
print(svc_confusion_mtx)

#finding Classification Report
svc_classification_rpt = classification_report(y_test,y_svc_pred)
print(svc_classification_rpt)

[[65 35]
 [26 74]]
              precision    recall  f1-score   support

           0       0.71      0.65      0.68       100
           1       0.68      0.74      0.71       100

    accuracy                           0.69       200
   macro avg       0.70      0.70      0.69       200
weighted avg       0.70      0.69      0.69       200

Decision Tree

In [14]:
#Decision Tree Model

dt_params = {
    "criterion"    : ["gini", "entropy", "log_loss"],
    "splitter"     : ["best", "random"],
    "max_features" : ["sqrt", "log2"]
}

dt_classifier = GridSearchCV(DecisionTreeClassifier(),dt_params, refit = True)  
dt_classifier.fit(x_train,y_train) 
print(dt_classifier.best_params_)

{'criterion': 'log_loss', 'max_features': 'sqrt', 'splitter': 'best'}

In [15]:
# dt_classifier = DecisionTreeClassifier()
# dt_classifier.fit(x_train,y_train)

In [16]:
#Predicting
y_dt_pred = dt_classifier.predict(x_test)

#finding Confustion Matrix
dt_confusion_mtx = confusion_matrix(y_test,y_dt_pred)
print(dt_confusion_mtx)

#finding Classification Report
dt_classification_rpt = classification_report(y_test,y_dt_pred)
print(dt_classification_rpt)

[[62 38]
 [41 59]]
              precision    recall  f1-score   support

           0       0.60      0.62      0.61       100
           1       0.61      0.59      0.60       100

    accuracy                           0.60       200
   macro avg       0.61      0.60      0.60       200
weighted avg       0.61      0.60      0.60       200

Random Forest Model

In [17]:
# #Random Forest Model

rf_params = {
    "criterion"    : ["gini", "entropy", "log_loss"],
    "n_estimators" : [50,100,250,500,1000],
    "max_features" : ["sqrt", "log2",None]
}

rf_classifier = GridSearchCV(RandomForestClassifier(),rf_params, refit = True)  
rf_classifier.fit(x_train,y_train) 
print(rf_classifier.best_params_)

{'criterion': 'gini', 'max_features': 'log2', 'n_estimators': 500}

In [18]:
#Random Forest Model Creation
# rf_classifier = RandomForestClassifier()
# rf_classifier.fit(x_train,y_train)

In [19]:
#Predicting
y_rf_pred = rf_classifier.predict(x_test)

#finding Confustion Matrix
rf_confusion_mtx = confusion_matrix(y_test,y_rf_pred)
print(rf_confusion_mtx)

#finding Classification Report
rf_classification_rpt = classification_report(y_test,y_rf_pred)
print(rf_classification_rpt)

[[62 38]
 [29 71]]
              precision    recall  f1-score   support

           0       0.68      0.62      0.65       100
           1       0.65      0.71      0.68       100

    accuracy                           0.67       200
   macro avg       0.67      0.67      0.66       200
weighted avg       0.67      0.67      0.66       200

Logistic Regression Model

In [20]:
# #Logistic Regression Model

lg_params = {       
    "C"   : [1.0,5.0,10.0],   
}

lg_classifier = GridSearchCV(LogisticRegression(),lg_params, refit = True)  
lg_classifier.fit(x_train,y_train) 
print(lg_classifier.best_params_)

{'C': 1.0}

In [21]:
#Logistic Regression Model Creation
# lg_classifier = LogisticRegression()
# lg_classifier.fit(x_train,y_train)

In [22]:
#Predicting
y_lg_pred = lg_classifier.predict(x_test)

#finding Confustion Matrix
lg_confusion_mtx = confusion_matrix(y_test,y_lg_pred)
print(lg_confusion_mtx)

#finding Classification Report
lg_classification_rpt = classification_report(y_test,y_lg_pred)
print(lg_classification_rpt)

[[64 36]
 [28 72]]
              precision    recall  f1-score   support

           0       0.70      0.64      0.67       100
           1       0.67      0.72      0.69       100

    accuracy                           0.68       200
   macro avg       0.68      0.68      0.68       200
weighted avg       0.68      0.68      0.68       200

KNN Model

In [34]:
# #Knn Model

knn_params = {    
    "n_neighbors" : [5,10,100,150,200],
    "algorithm"   : ["auto", "ball_tree", "kd_tree", "brute"],
    "metric" : ["minkowski"]    
}

knn_classifier = GridSearchCV(KNeighborsClassifier(),knn_params, refit = True)  
knn_classifier.fit(x_train,y_train) 
print(knn_classifier.best_params_)

{'algorithm': 'auto', 'metric': 'minkowski', 'n_neighbors': 100}

In [ ]:
# knn_classifier = KNeighborsClassifier(n_neighbors=5,metric='minkowski')
# knn_classifier.fit(x_test,y_test)

In [35]:
#Predicting
y_knn_pred = knn_classifier.predict(x_test)
 
threshold = 0.5
y_knn_pred_binary = (y_knn_pred > threshold).astype(int)
    
#finding Confustion Matrix
knn_confusion_mtx = confusion_matrix(y_test,y_knn_pred_binary)
print(knn_confusion_mtx)

#finding Classification Report
knn_classification_rpt = classification_report(y_test,y_knn_pred_binary)
print(knn_classification_rpt)

[[63 37]
 [31 69]]
              precision    recall  f1-score   support

           0       0.67      0.63      0.65       100
           1       0.65      0.69      0.67       100

    accuracy                           0.66       200
   macro avg       0.66      0.66      0.66       200
weighted avg       0.66      0.66      0.66       200

Naive Baye Model

In [24]:
#Gaussian Naive Baye
nbgb_regressor = GaussianNB()
nbgb_regressor.fit(x_train,y_train)

GaussianNB()

In [25]:
nbgb_y_pred = nbgb_regressor.predict(x_test)
nbgb_y_pred_metrics_report = classification_report(y_test,nbgb_y_pred)
print(nbgb_y_pred_metrics_report)

              precision    recall  f1-score   support

           0       0.70      0.64      0.67       100
           1       0.67      0.73      0.70       100

    accuracy                           0.69       200
   macro avg       0.69      0.69      0.68       200
weighted avg       0.69      0.69      0.68       200

In [26]:
x1_train,x1_test,y1_train,y1_test = train_test_split(independent,dependent, test_size = 0.2,stratify = dependent,random_state = 42)

In [27]:
#Multinomial Naive Baye
nbmn_regressor = MultinomialNB()
nbmn_regressor.fit(x1_train,y1_train)

MultinomialNB()

In [28]:
nbmn_y_pred = nbmn_regressor.predict(x1_test)
nbmv_y_pred_metrics_report = classification_report(y1_test,nbmn_y_pred)
print(nbmv_y_pred_metrics_report)

              precision    recall  f1-score   support

           0       0.56      0.57      0.56       100
           1       0.56      0.55      0.56       100

    accuracy                           0.56       200
   macro avg       0.56      0.56      0.56       200
weighted avg       0.56      0.56      0.56       200

In [29]:
#Complement Naive Baye
nbcm_regressor = ComplementNB()
nbcm_regressor.fit(x1_train,y1_train)

ComplementNB()

In [30]:
nbcm_y_pred = nbcm_regressor.predict(x1_test)
nbcm_y_pred_metrics_report = classification_report(y1_test,nbcm_y_pred)
print(nbcm_y_pred_metrics_report)

              precision    recall  f1-score   support

           0       0.56      0.57      0.56       100
           1       0.56      0.55      0.56       100

    accuracy                           0.56       200
   macro avg       0.56      0.56      0.56       200
weighted avg       0.56      0.56      0.56       200

In [31]:
#Bernoulli Naive Baye
nbbl_regressor = BernoulliNB()
nbbl_regressor.fit(x1_train,y1_train)

BernoulliNB()

In [32]:
nbbl_y_pred = nbbl_regressor.predict(x1_test)
nbbl_y_pred_metrics_report = classification_report(y1_test,nbbl_y_pred)
print(nbbl_y_pred_metrics_report)

              precision    recall  f1-score   support

           0       0.56      0.51      0.53       100
           1       0.55      0.60      0.57       100

    accuracy                           0.56       200
   macro avg       0.56      0.55      0.55       200
weighted avg       0.56      0.56      0.55       200

In [33]:
#Saving the Model (Random Forest Accuracy: 91)

pickle.dump(rf_classifier,open("Predictor_Final_Model.sav","wb"))