In [1]:
#Loading Libraries
import pandas as pd
import pickle
import warnings
import numpy as np
from sklearn.svm import SVC
from sklearn.impute import SimpleImputer
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import ComplementNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import CategoricalNB 
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
warnings.filterwarnings("ignore")

In [3]:
#Loading Dataset
dataset = pd.read_csv("Preprocessed_Dataset_Numerical.csv")
dataset

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education_High School,...,MaritalStatus_Married,MaritalStatus_Single,HasMortgage_Yes,HasDependents_Yes,LoanPurpose_Business,LoanPurpose_Education,LoanPurpose_Home,LoanPurpose_Other,HasCoSigner_Yes,Default
0,57.0,109874.0,30973.0,567.0,113.0,4.0,13.95,60.0,0.62,0,...,0,0,1,1,0,0,0,0,0,0
1,69.0,34006.0,112148.0,597.0,10.0,4.0,10.60,24.0,0.41,0,...,1,0,0,1,0,0,0,0,1,1
2,20.0,36779.0,135741.0,352.0,75.0,4.0,23.82,36.0,0.84,0,...,0,0,1,0,0,0,0,0,0,1
3,41.0,50628.0,82083.0,828.0,102.0,1.0,11.32,48.0,0.46,1,...,0,0,1,0,0,0,0,0,0,1
4,28.0,114840.0,246968.0,415.0,109.0,4.0,22.65,24.0,0.73,1,...,0,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,20.0,143934.0,105532.0,521.0,31.0,3.0,14.66,24.0,0.48,0,...,1,0,0,1,0,0,0,0,1,1
49996,47.0,139079.0,102610.0,669.0,82.0,3.0,17.28,24.0,0.21,0,...,0,0,1,1,0,0,0,0,0,0
49997,32.0,106367.0,85207.0,466.0,34.0,1.0,2.44,36.0,0.83,0,...,0,0,1,0,0,0,0,0,0,0
49998,29.0,94936.0,45806.0,313.0,44.0,4.0,24.81,48.0,0.83,0,...,0,1,1,1,0,0,0,0,1,1
49999,28.0,115166.0,211439.0,461.0,41.0,1.0,24.79,60.0,0.59,0,...,0,0,0,1,0,0,0,0,1,1

In [4]:
dataset.columns

Index(['Age', 'Income', 'LoanAmount', 'CreditScore', 'MonthsEmployed',
       'NumCreditLines', 'InterestRate', 'LoanTerm', 'DTIRatio',
       'Education_High School', 'Education_Master's', 'Education_PhD',
       'EmploymentType_Part-time', 'EmploymentType_Self-employed',
       'EmploymentType_Unemployed', 'MaritalStatus_Married',
       'MaritalStatus_Single', 'HasMortgage_Yes', 'HasDependents_Yes',
       'LoanPurpose_Business', 'LoanPurpose_Education', 'LoanPurpose_Home',
       'LoanPurpose_Other', 'HasCoSigner_Yes', 'Default'],
      dtype='object')

In [5]:
independent = dataset.drop(["Default"],axis = 1)
dependent = dataset[["Default"]]

In [6]:
independent.head()

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education_High School,...,EmploymentType_Unemployed,MaritalStatus_Married,MaritalStatus_Single,HasMortgage_Yes,HasDependents_Yes,LoanPurpose_Business,LoanPurpose_Education,LoanPurpose_Home,LoanPurpose_Other,HasCoSigner_Yes
0,57.0,109874.0,30973.0,567.0,113.0,4.0,13.95,60.0,0.62,0,...,0,0,0,1,1,0,0,0,0,0
1,69.0,34006.0,112148.0,597.0,10.0,4.0,10.60,24.0,0.41,0,...,0,1,0,0,1,0,0,0,0,1
2,20.0,36779.0,135741.0,352.0,75.0,4.0,23.82,36.0,0.84,0,...,0,0,0,1,0,0,0,0,0,0
3,41.0,50628.0,82083.0,828.0,102.0,1.0,11.32,48.0,0.46,1,...,0,0,0,1,0,0,0,0,0,0
4,28.0,114840.0,246968.0,415.0,109.0,4.0,22.65,24.0,0.73,1,...,0,0,0,0,1,0,0,0,0,1

In [7]:
dependent.head()

   Default
0        0
1        1
2        1
3        1
4        0

In [8]:
independent.isnull().sum()

Age                             0
Income                          0
LoanAmount                      0
CreditScore                     0
MonthsEmployed                  0
NumCreditLines                  0
InterestRate                    0
LoanTerm                        0
DTIRatio                        0
Education_High School           0
Education_Master's              0
Education_PhD                   0
EmploymentType_Part-time        0
EmploymentType_Self-employed    0
EmploymentType_Unemployed       0
MaritalStatus_Married           0
MaritalStatus_Single            0
HasMortgage_Yes                 0
HasDependents_Yes               0
LoanPurpose_Business            0
LoanPurpose_Education           0
LoanPurpose_Home                0
LoanPurpose_Other               0
HasCoSigner_Yes                 0
dtype: int64

In [9]:
x_train,x_test,y_train,y_test = train_test_split(independent,dependent, test_size = 0.2,random_state = 42)

In [10]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
x_train

array([[-0.84192112, -1.56617985,  0.30910893, ...,  0.        ,
         0.        ,  1.04349505],
       [ 1.36383457,  1.77732022,  1.40731332, ...,  0.        ,
         0.        , -0.95831791],
       [-0.24035138, -0.07051643,  0.79830945, ...,  0.        ,
         0.        ,  1.04349505],
       ...,
       [-0.44087463,  1.41372057, -0.23870256, ...,  0.        ,
         0.        , -0.95831791],
       [ 0.16069511, -0.3882607 ,  0.02989222, ...,  0.        ,
         0.        ,  1.04349505],
       [-0.57455679, -0.83708447,  0.74960099, ...,  0.        ,
         0.        ,  1.04349505]])

 SVM Model

In [11]:
# svc_params = {   
#    "kernel" : ["rbf","sigmoid","linear"],   
#    "C"      : [100,150],     
#    "gamma"   : ["scale", "auto"]
# }
# svc_classifier = GridSearchCV(SVC(),svc_params, refit = True)  
# svc_classifier.fit(x_train,y_train) 
# print(svc_classifier.best_params_)

In [12]:
svc_classifier = SVC()
svc_classifier.fit(x_train,y_train)

SVC()

In [13]:
#Predicting
y_svc_pred = svc_classifier.predict(x_test)

#finding Confustion Matrix
svc_confusion_mtx = confusion_matrix(y_test,y_svc_pred)
print(svc_confusion_mtx)

#finding Classification Report
svc_classification_rpt = classification_report(y_test,y_svc_pred)
print(svc_classification_rpt)

[[3296 1676]
 [1602 3426]]
              precision    recall  f1-score   support

           0       0.67      0.66      0.67      4972
           1       0.67      0.68      0.68      5028

    accuracy                           0.67     10000
   macro avg       0.67      0.67      0.67     10000
weighted avg       0.67      0.67      0.67     10000

Decision Tree

In [14]:
#Decision Tree Model

# dt_params = {
#     "criterion"    : ["gini", "entropy", "log_loss"],
#     "splitter"     : ["best", "random"],
#     "max_features" : ["sqrt", "log2"]
# }

# dt_classifier = GridSearchCV(DecisionTreeClassifier(),dt_params, refit = True)  
# dt_classifier.fit(x_train,y_train) 
# print(dt_classifier.best_params_)

In [15]:
dt_classifier = DecisionTreeClassifier()
dt_classifier.fit(x_train,y_train)

DecisionTreeClassifier()

In [16]:
#Predicting
y_dt_pred = dt_classifier.predict(x_test)

#finding Confustion Matrix
dt_confusion_mtx = confusion_matrix(y_test,y_dt_pred)
print(dt_confusion_mtx)

#finding Classification Report
dt_classification_rpt = classification_report(y_test,y_dt_pred)
print(dt_classification_rpt)

[[2957 2015]
 [2067 2961]]
              precision    recall  f1-score   support

           0       0.59      0.59      0.59      4972
           1       0.60      0.59      0.59      5028

    accuracy                           0.59     10000
   macro avg       0.59      0.59      0.59     10000
weighted avg       0.59      0.59      0.59     10000

Random Forest Model

In [17]:
# #Random Forest Model

# rf_params = {
#     "criterion"    : ["gini", "entropy", "log_loss"],
#     "n_estimators" : [50,100,250,500,1000],
#     "max_features" : ["sqrt", "log2",None]
# }

# rf_classifier = GridSearchCV(RandomForestClassifier(),rf_params, refit = True)  
# rf_classifier.fit(x_train,y_train) 
# print(rf_classifier.best_params_)

In [18]:
#Random Forest Model Creation
rf_classifier = RandomForestClassifier()
rf_classifier.fit(x_train,y_train)

RandomForestClassifier()

In [19]:
#Predicting
y_rf_pred = rf_classifier.predict(x_test)

#finding Confustion Matrix
rf_confusion_mtx = confusion_matrix(y_test,y_rf_pred)
print(rf_confusion_mtx)

#finding Classification Report
rf_classification_rpt = classification_report(y_test,y_rf_pred)
print(rf_classification_rpt)

[[3320 1652]
 [1693 3335]]
              precision    recall  f1-score   support

           0       0.66      0.67      0.66      4972
           1       0.67      0.66      0.67      5028

    accuracy                           0.67     10000
   macro avg       0.67      0.67      0.67     10000
weighted avg       0.67      0.67      0.67     10000

Logistic Regression Model

In [20]:
# #Logistic Regression Model

# lg_params = {       
#     "C"   : [1.0,5.0,10.0],   
# }

# lg_classifier = GridSearchCV(LogisticRegression(),lg_params, refit = True)  
# lg_classifier.fit(x_train,y_train) 
# print(lg_classifier.best_params_)

In [21]:
#Logistic Regression Model Creation
lg_classifier = LogisticRegression()
lg_classifier.fit(x_train,y_train)

LogisticRegression()

In [22]:
#Predicting
y_lg_pred = lg_classifier.predict(x_test)

#finding Confustion Matrix
lg_confusion_mtx = confusion_matrix(y_test,y_lg_pred)
print(lg_confusion_mtx)

#finding Classification Report
lg_classification_rpt = classification_report(y_test,y_lg_pred)
print(lg_classification_rpt)

[[3313 1659]
 [1579 3449]]
              precision    recall  f1-score   support

           0       0.68      0.67      0.67      4972
           1       0.68      0.69      0.68      5028

    accuracy                           0.68     10000
   macro avg       0.68      0.68      0.68     10000
weighted avg       0.68      0.68      0.68     10000

KNN Model

In [23]:
# #Knn Model

# knn_params = {    
#     "n_neighbors" : [5,10,100,150,200],
#     "algorithm"   : ["auto", "ball_tree", "kd_tree", "brute"],
#     "metric" : ["minkowski"]    
# }

# knn_classifier = GridSearchCV(KNeighborsRegressor(),knn_params, refit = True)  
# knn_classifier.fit(x_train,y_train) 
# print(knn_classifier.best_params_)

In [24]:
knn_regressor = KNeighborsClassifier(n_neighbors=5,metric='minkowski')
knn_regressor.fit(x_test,y_test)

NameError: name 'KNeighborsClassifier' is not defined

In [ ]:
#Predicting
y_knn_pred = knn_classifier.predict(x_test)
 
threshold = 0.5
y_knn_pred_binary = (y_knn_pred > threshold).astype(int)
    
#finding Confustion Matrix
knn_confusion_mtx = confusion_matrix(y_test,y_knn_pred_binary)
print(knn_confusion_mtx)

#finding Classification Report
knn_classification_rpt = classification_report(y_test,y_knn_pred_binary)
print(knn_classification_rpt)

Naive Baye Model

In [ ]:
#Gaussian Naive Baye
nbgb_regressor = GaussianNB()
nbgb_regressor.fit(x_train,y_train)

In [ ]:
nbgb_y_pred = nbgb_regressor.predict(x_test)
nbgb_y_pred_metrics_report = classification_report(y_test,nbgb_y_pred)
print(nbgb_y_pred_metrics_report)

In [ ]:
x1_train,x1_test,y1_train,y1_test = train_test_split(independent,dependent, test_size = 0.2,stratify = dependent,random_state = 42)

In [ ]:
#Multinomial Naive Baye
nbmn_regressor = MultinomialNB()
nbmn_regressor.fit(x1_train,y1_train)

In [ ]:
nbmn_y_pred = nbmn_regressor.predict(x1_test)
nbmv_y_pred_metrics_report = classification_report(y1_test,nbmn_y_pred)
print(nbmv_y_pred_metrics_report)

In [ ]:
#Complement Naive Baye
nbcm_regressor = ComplementNB()
nbcm_regressor.fit(x1_train,y1_train)

In [ ]:
nbcm_y_pred = nbcm_regressor.predict(x1_test)
nbcm_y_pred_metrics_report = classification_report(y1_test,nbcm_y_pred)
print(nbcm_y_pred_metrics_report)

In [ ]:
#Bernoulli Naive Baye
nbbl_regressor = BernoulliNB()
nbbl_regressor.fit(x1_train,y1_train)

In [ ]:
nbbl_y_pred = nbbl_regressor.predict(x1_test)
nbbl_y_pred_metrics_report = classification_report(y1_test,nbbl_y_pred)
print(nbbl_y_pred_metrics_report)

In [ ]:
#Saving the Model (Random Forest Accuracy: 91)

pickle.dump(rf_classifier,open("Predictor_Final_Model.sav","wb"))