In [1]:
#Importing Libraries
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer

In [2]:
#Loading Dataset
dataset = pd.read_csv("Balanced_Dataset.csv")

In [3]:
dataset

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
0,57.0,109874,30973,567,113,4,13.95,60,0.62,Master's,Part-time,Divorced,Yes,Yes,Auto,No,0
1,69.0,34006,112148,597,10,4,10.60,24,0.41,Master's,Part-time,Married,No,Yes,Home,Yes,1
2,20.0,36779,135741,352,75,4,23.82,36,0.84,Bachelor's,Full-time,Divorced,Yes,No,Auto,No,1
3,41.0,50628,82083,828,102,1,11.32,48,0.46,High School,Self-employed,Divorced,Yes,No,Auto,No,1
4,28.0,114840,246968,415,109,4,22.65,24,0.73,High School,Self-employed,Divorced,No,Yes,Home,Yes,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,20.0,143934,105532,521,31,3,14.66,24,0.48,Bachelor's,Self-employed,Married,No,Yes,Business,Yes,1
49996,47.0,139079,102610,669,82,3,17.28,24,0.21,PhD,Unemployed,Divorced,Yes,Yes,Auto,No,0
49997,32.0,106367,85207,466,34,1,2.44,36,0.83,Bachelor's,Self-employed,Divorced,Yes,No,Business,No,0
49998,29.0,94936,45806,313,44,4,24.81,48,0.83,PhD,Full-time,Single,Yes,Yes,Home,Yes,1
49999,28.0,115166,211439,461,41,1,24.79,60,0.59,Master's,Full-time,Divorced,No,Yes,Other,Yes,1

In [4]:
dataset.isnull().sum()

Age               1
Income            0
LoanAmount        0
CreditScore       0
MonthsEmployed    0
NumCreditLines    0
InterestRate      0
LoanTerm          0
DTIRatio          0
Education         0
EmploymentType    0
MaritalStatus     0
HasMortgage       2
HasDependents     0
LoanPurpose       1
HasCoSigner       0
Default           0
dtype: int64

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             49999 non-null  float64
 1   Income          50000 non-null  int64
 2   LoanAmount      50000 non-null  int64
 3   CreditScore     50000 non-null  int64
 4   MonthsEmployed  50000 non-null  int64
 5   NumCreditLines  50000 non-null  int64
 6   InterestRate    50000 non-null  float64
 7   LoanTerm        50000 non-null  int64
 8   DTIRatio        50000 non-null  float64
 9   Education       50000 non-null  object
 10  EmploymentType  50000 non-null  object
 11  MaritalStatus   50000 non-null  object
 12  HasMortgage     49998 non-null  object
 13  HasDependents   50000 non-null  object
 14  LoanPurpose     49999 non-null  object
 15  HasCoSigner     50000 non-null  object
 16  Default         50000 non-null  int64
dtypes: float64(3), int64(7), object(7)
memory usage: 6.5+ MB

In [6]:
independent = dataset.drop("Default", axis = 1)
dependent = dataset["Default"]

In [7]:
dependent

0        0
1        1
2        1
3        1
4        0
        ..
49995    1
49996    0
49997    0
49998    1
49999    1
Name: Default, Length: 50000, dtype: int64

In [8]:
independent

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner
0,57.0,109874,30973,567,113,4,13.95,60,0.62,Master's,Part-time,Divorced,Yes,Yes,Auto,No
1,69.0,34006,112148,597,10,4,10.60,24,0.41,Master's,Part-time,Married,No,Yes,Home,Yes
2,20.0,36779,135741,352,75,4,23.82,36,0.84,Bachelor's,Full-time,Divorced,Yes,No,Auto,No
3,41.0,50628,82083,828,102,1,11.32,48,0.46,High School,Self-employed,Divorced,Yes,No,Auto,No
4,28.0,114840,246968,415,109,4,22.65,24,0.73,High School,Self-employed,Divorced,No,Yes,Home,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,20.0,143934,105532,521,31,3,14.66,24,0.48,Bachelor's,Self-employed,Married,No,Yes,Business,Yes
49996,47.0,139079,102610,669,82,3,17.28,24,0.21,PhD,Unemployed,Divorced,Yes,Yes,Auto,No
49997,32.0,106367,85207,466,34,1,2.44,36,0.83,Bachelor's,Self-employed,Divorced,Yes,No,Business,No
49998,29.0,94936,45806,313,44,4,24.81,48,0.83,PhD,Full-time,Single,Yes,Yes,Home,Yes
49999,28.0,115166,211439,461,41,1,24.79,60,0.59,Master's,Full-time,Divorced,No,Yes,Other,Yes

In [9]:
#Splitting into Numerical and Categorical Data
numerical_data = independent.select_dtypes(include = [np.number])
categorical_data = independent.select_dtypes(exclude = [np.number])

In [10]:
categorical_data

,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner
0,Master's,Part-time,Divorced,Yes,Yes,Auto,No
1,Master's,Part-time,Married,No,Yes,Home,Yes
2,Bachelor's,Full-time,Divorced,Yes,No,Auto,No
3,High School,Self-employed,Divorced,Yes,No,Auto,No
4,High School,Self-employed,Divorced,No,Yes,Home,Yes
...,...,...,...,...,...,...,...
49995,Bachelor's,Self-employed,Married,No,Yes,Business,Yes
49996,PhD,Unemployed,Divorced,Yes,Yes,Auto,No
49997,Bachelor's,Self-employed,Divorced,Yes,No,Business,No
49998,PhD,Full-time,Single,Yes,Yes,Home,Yes
49999,Master's,Full-time,Divorced,No,Yes,Other,Yes

In [11]:
numerical_data

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio
0,57.0,109874,30973,567,113,4,13.95,60,0.62
1,69.0,34006,112148,597,10,4,10.60,24,0.41
2,20.0,36779,135741,352,75,4,23.82,36,0.84
3,41.0,50628,82083,828,102,1,11.32,48,0.46
4,28.0,114840,246968,415,109,4,22.65,24,0.73
...,...,...,...,...,...,...,...,...,...
49995,20.0,143934,105532,521,31,3,14.66,24,0.48
49996,47.0,139079,102610,669,82,3,17.28,24,0.21
49997,32.0,106367,85207,466,34,1,2.44,36,0.83
49998,29.0,94936,45806,313,44,4,24.81,48,0.83
49999,28.0,115166,211439,461,41,1,24.79,60,0.59

In [12]:
imputer = SimpleImputer(strategy = "mean")

In [13]:
imputer.fit(numerical_data[::])

SimpleImputer()

In [14]:
numerical_filled_data = pd.DataFrame(imputer.fit_transform(numerical_data), columns = numerical_data.columns)

In [15]:
numerical_filled_data.isnull().sum()

Age               0
Income            0
LoanAmount        0
CreditScore       0
MonthsEmployed    0
NumCreditLines    0
InterestRate      0
LoanTerm          0
DTIRatio          0
dtype: int64

In [16]:
categorical_imputer = SimpleImputer(strategy = "most_frequent")

In [17]:
categorical_filled_data = pd.DataFrame(categorical_imputer.fit_transform(categorical_data), columns = categorical_data.columns)

In [18]:
categorical_filled_data.isnull().sum()

Education         0
EmploymentType    0
MaritalStatus     0
HasMortgage       0
HasDependents     0
LoanPurpose       0
HasCoSigner       0
dtype: int64

In [19]:
independent = pd.concat([numerical_filled_data,categorical_filled_data], axis = 1)

In [20]:
independent

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner
0,57.0,109874.0,30973.0,567.0,113.0,4.0,13.95,60.0,0.62,Master's,Part-time,Divorced,Yes,Yes,Auto,No
1,69.0,34006.0,112148.0,597.0,10.0,4.0,10.60,24.0,0.41,Master's,Part-time,Married,No,Yes,Home,Yes
2,20.0,36779.0,135741.0,352.0,75.0,4.0,23.82,36.0,0.84,Bachelor's,Full-time,Divorced,Yes,No,Auto,No
3,41.0,50628.0,82083.0,828.0,102.0,1.0,11.32,48.0,0.46,High School,Self-employed,Divorced,Yes,No,Auto,No
4,28.0,114840.0,246968.0,415.0,109.0,4.0,22.65,24.0,0.73,High School,Self-employed,Divorced,No,Yes,Home,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,20.0,143934.0,105532.0,521.0,31.0,3.0,14.66,24.0,0.48,Bachelor's,Self-employed,Married,No,Yes,Business,Yes
49996,47.0,139079.0,102610.0,669.0,82.0,3.0,17.28,24.0,0.21,PhD,Unemployed,Divorced,Yes,Yes,Auto,No
49997,32.0,106367.0,85207.0,466.0,34.0,1.0,2.44,36.0,0.83,Bachelor's,Self-employed,Divorced,Yes,No,Business,No
49998,29.0,94936.0,45806.0,313.0,44.0,4.0,24.81,48.0,0.83,PhD,Full-time,Single,Yes,Yes,Home,Yes
49999,28.0,115166.0,211439.0,461.0,41.0,1.0,24.79,60.0,0.59,Master's,Full-time,Divorced,No,Yes,Other,Yes

In [21]:
independent.isnull().sum()

Age               0
Income            0
LoanAmount        0
CreditScore       0
MonthsEmployed    0
NumCreditLines    0
InterestRate      0
LoanTerm          0
DTIRatio          0
Education         0
EmploymentType    0
MaritalStatus     0
HasMortgage       0
HasDependents     0
LoanPurpose       0
HasCoSigner       0
dtype: int64

In [22]:
dependent

0        0
1        1
2        1
3        1
4        0
        ..
49995    1
49996    0
49997    0
49998    1
49999    1
Name: Default, Length: 50000, dtype: int64

In [28]:
preprocessed_dataset = pd.concat([independent, dependent],axis = 1)
preprocessed_dataset

TypeError: concat() got an unexpected keyword argument 'index'

In [29]:
preprocessed_dataset.to_csv("Preprocessed_Dataset.csv",index = False)

# Feature Selection

In [24]:
independent = pd.get_dummies(independent,dtype= int,drop_first = True)
independent

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education_High School,...,EmploymentType_Unemployed,MaritalStatus_Married,MaritalStatus_Single,HasMortgage_Yes,HasDependents_Yes,LoanPurpose_Business,LoanPurpose_Education,LoanPurpose_Home,LoanPurpose_Other,HasCoSigner_Yes
0,57.0,109874.0,30973.0,567.0,113.0,4.0,13.95,60.0,0.62,0,...,0,0,0,1,1,0,0,0,0,0
1,69.0,34006.0,112148.0,597.0,10.0,4.0,10.60,24.0,0.41,0,...,0,1,0,0,1,0,0,1,0,1
2,20.0,36779.0,135741.0,352.0,75.0,4.0,23.82,36.0,0.84,0,...,0,0,0,1,0,0,0,0,0,0
3,41.0,50628.0,82083.0,828.0,102.0,1.0,11.32,48.0,0.46,1,...,0,0,0,1,0,0,0,0,0,0
4,28.0,114840.0,246968.0,415.0,109.0,4.0,22.65,24.0,0.73,1,...,0,0,0,0,1,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,20.0,143934.0,105532.0,521.0,31.0,3.0,14.66,24.0,0.48,0,...,0,1,0,0,1,1,0,0,0,1
49996,47.0,139079.0,102610.0,669.0,82.0,3.0,17.28,24.0,0.21,0,...,1,0,0,1,1,0,0,0,0,0
49997,32.0,106367.0,85207.0,466.0,34.0,1.0,2.44,36.0,0.83,0,...,0,0,0,1,0,1,0,0,0,0
49998,29.0,94936.0,45806.0,313.0,44.0,4.0,24.81,48.0,0.83,0,...,0,0,1,1,1,0,0,1,0,1
49999,28.0,115166.0,211439.0,461.0,41.0,1.0,24.79,60.0,0.59,0,...,0,0,0,0,1,0,0,0,1,1

In [25]:
preprocessed_dataset_numerical = pd.concat([independent, dependent],axis = 1)
preprocessed_dataset_numerical

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education_High School,...,MaritalStatus_Married,MaritalStatus_Single,HasMortgage_Yes,HasDependents_Yes,LoanPurpose_Business,LoanPurpose_Education,LoanPurpose_Home,LoanPurpose_Other,HasCoSigner_Yes,Default
0,57.0,109874.0,30973.0,567.0,113.0,4.0,13.95,60.0,0.62,0,...,0,0,1,1,0,0,0,0,0,0
1,69.0,34006.0,112148.0,597.0,10.0,4.0,10.60,24.0,0.41,0,...,1,0,0,1,0,0,1,0,1,1
2,20.0,36779.0,135741.0,352.0,75.0,4.0,23.82,36.0,0.84,0,...,0,0,1,0,0,0,0,0,0,1
3,41.0,50628.0,82083.0,828.0,102.0,1.0,11.32,48.0,0.46,1,...,0,0,1,0,0,0,0,0,0,1
4,28.0,114840.0,246968.0,415.0,109.0,4.0,22.65,24.0,0.73,1,...,0,0,0,1,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,20.0,143934.0,105532.0,521.0,31.0,3.0,14.66,24.0,0.48,0,...,1,0,0,1,1,0,0,0,1,1
49996,47.0,139079.0,102610.0,669.0,82.0,3.0,17.28,24.0,0.21,0,...,0,0,1,1,0,0,0,0,0,0
49997,32.0,106367.0,85207.0,466.0,34.0,1.0,2.44,36.0,0.83,0,...,0,0,1,0,1,0,0,0,0,0
49998,29.0,94936.0,45806.0,313.0,44.0,4.0,24.81,48.0,0.83,0,...,0,1,1,1,0,0,1,0,1,1
49999,28.0,115166.0,211439.0,461.0,41.0,1.0,24.79,60.0,0.59,0,...,0,0,0,1,0,0,0,1,1,1

In [30]:
preprocessed_dataset_numerical.to_csv("Preprocessed_Dataset_Numerical.csv",index = False)